# Generated by Django 3.2.4 on 2021-06-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
