# Generated by Django 3.2.4 on 2021-07-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
